# Generated by Django 4.2.6 on 2023-11-14 15:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('englishName', models.CharField(max_length=150)),
                ('maxMablagh', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etebar', models.BigIntegerField(blank=True, null=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Takhfif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('darsad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expierDate', django_jalali.db.models.jDateField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('state', models.BooleanField()),
                ('copnTakhfif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.takhfif')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='DafterAqhsat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('tedad', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.member')),
            ],
        ),
        migrations.CreateModel(
            name='Aqhsat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikhSarresid', django_jalali.db.models.jDateField()),
                ('tarikhPardakht', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('mablagh', models.BigIntegerField()),
                ('aghsat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.dafteraqhsat')),
            ],
        ),
    ]
