# Generated by Django 4.2.6 on 2023-11-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='copnTakhfif',
        ),
    ]
