# Generated by Django 4.2.6 on 2023-11-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('customer', '0002_remove_sabad_copntakhfif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='product',
        ),
        migrations.AddField(
            model_name='sabad',
            name='mablag',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductSabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
                ('sabad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.sabad')),
            ],
        ),
    ]
