# Generated by Django 4.2.6 on 2023-11-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('customer', '0004_productsabad_tedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role'),
        ),
    ]
