# Generated by Django 4.2.6 on 2023-11-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_faktor_liststate_listprudoct_faktor_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dafteraqhsat',
            name='member',
        ),
        migrations.AddField(
            model_name='dafteraqhsat',
            name='faktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.faktor'),
        ),
        migrations.AlterField(
            model_name='aqhsat',
            name='aghsat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.dafteraqhsat'),
        ),
        migrations.AlterField(
            model_name='faktor',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.member'),
        ),
    ]
