# Generated by Django 4.2.6 on 2023-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_dafteraqhsat_member_dafteraqhsat_faktor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liststate',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
