# Generated by Django 4.2.6 on 2023-11-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_liststate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listprudoct',
            name='Faktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.faktor'),
        ),
    ]
