# Generated by Django 4.2.6 on 2023-11-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('customer', '0009_alter_listprudoct_faktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listprudoct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
