# Generated by Django 4.2.6 on 2023-11-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('customer', '0011_alter_productsabad_product_alter_productsabad_sabad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListPrudoct',
            new_name='FaktorProduct',
        ),
    ]
