# Generated by Django 4.2.6 on 2023-11-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_faktorproduct_productfaktor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfaktor',
            old_name='Faktor',
            new_name='faktor',
        ),
    ]
