# Generated by Django 4.2.6 on 2023-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_rename_faktor_productfaktor_faktor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqhsat',
            name='namber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
