# Generated by Django 4.2.6 on 2023-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_aqhsat_namber'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfaktor',
            name='tedad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
