# Generated by Django 4.2.6 on 2023-11-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_rename_date_sabad_creatdate_rename_mablag_sabad_sum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='state',
        ),
    ]
