# Generated by Django 4.2.6 on 2023-11-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_sabad_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.liststate'),
        ),
    ]
