# Generated by Django 4.2.6 on 2023-11-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_sabad_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststate',
            name='englishName',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
