# Generated by Django 4.2.6 on 2023-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_liststate_englishname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktor',
            name='pardakht',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faktor',
            name='sum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faktor',
            name='takhfif',
            field=models.IntegerField(default=0),
        ),
    ]
