# Generated by Django 4.2.6 on 2023-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_remove_productfaktor_pricejam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfaktor',
            name='priceJam',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productfaktor',
            name='tedad',
            field=models.IntegerField(default=1),
        ),
    ]
