# Generated by Django 4.2.6 on 2023-11-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_productfaktor_pricejam_productfaktor_tedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfaktor',
            name='priceJam',
        ),
    ]
