# Generated by Django 4.2.6 on 2023-11-28 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_remove_productfaktor_pricejam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktor',
            name='takhfif',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='takhfif',
            name='darsad',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
