# Generated by Django 4.2.6 on 2023-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_faktor_pardakht'),
    ]

    operations = [
        migrations.AddField(
            model_name='takhfif',
            name='maximum',
            field=models.BigIntegerField(default=0),
        ),
    ]
