# Generated by Django 4.2.6 on 2023-11-30 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_remove_faktor_takhfif'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktor',
            name='takhfif',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
