# Generated by Django 4.2.6 on 2023-12-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_faktor_takhfif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqhsat',
            name='aghsat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.dafteraqhsat'),
        ),
    ]
