# Generated by Django 4.2.6 on 2023-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_slug'),
        ('customer', '0035_alter_aqhsat_aghsat'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktor',
            name='products',
            field=models.ManyToManyField(related_name='product_factor', to='shop.product'),
        ),
    ]
