# Generated by Django 4.2.6 on 2023-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='takhfif',
            field=models.BigIntegerField(default=0),
        ),
    ]
