# Generated by Django 4.2.6 on 2023-12-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_takhfif'),
    ]

    operations = [
        migrations.CreateModel(
            name='exeleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/exel')),
            ],
        ),
    ]
