# Generated by Django 4.2.6 on 2023-12-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_is_sub_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slage', unique=True),
            preserve_default=False,
        ),
    ]
