# Generated by Django 4.2.6 on 2023-12-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
