# Generated by Django 4.2.6 on 2023-12-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exeleFile',
        ),
    ]
