# Generated by Django 4.2.6 on 2023-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_catel2_catel1_delete_catel1_delete_catel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dasteh',
            field=models.ManyToManyField(related_name='dasteh_name', to='shop.daste'),
        ),
    ]
