# Generated by Django 4.2.6 on 2023-12-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_dasteh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DasteProduct',
        ),
    ]
